### ISSUE TITLE
Backwards-incompatible changes not mentioned in manual

### ISSUE THREAD

**Issue by lbteixeira** [st--/annotate-equations#13]
Hi. Thank you very much for this nice package, it is quite useful for me.

I believe I have found a bug in the pdf documentation. At some point, you mention that to change the font size/style, the following command should be used:

`\renewcommand{\eqnannotationfont}{\sffamily\tiny}`

When I do that, the compiler complains that the command \eqnannotationfont doesn't exist. When I check the sty file available in my installation (using MikTeX in Windows, if that matters) I can confirm that it really doesn't.

To change the font, this is the command that I had to include:

`\renewcommand{\eqnannotationtext}[1]{\sffamily\tiny#1\strut}`

By the way, it would be nice to have a way to change the color of the annotation (arrow and text) without changing the color of the equation or having to add a box around it. I did this by defining `\renewcommand{\eqnhighlightshade}{0}`, but this is a global option (for all annotations). There could be a way to do it for individual annotations. If you think this is interesting, I can try to implement and make a pull request.

**Comment by st--** [comment]
Hi @lbteixeira - can you check what version of the package you are using? #11, released in v0.2.0, fixed the issue with multi-line font settings, as part of which `\eqnannotationtext` (of v0.1.0) got removed and `\eqnannotationfont` was introduced instead. I pointed this out in the release notes but I'm now seeing I should have also added a comment to that effect to the manual :facepalm: I only released the new package last week, so it might take a while for it to show up in your distribution. (You could of course download the latest .sty file directly from this repository.)

Regarding the color, I'd prefer if it didn't introduce additional commands or increase the code complexity significantly - but if you can see an easy way of adding it, I'd be happy to discuss:)

**Comment by lbteixeira** [comment]
Indeed, I was using v0.1.0. I have changed now to v0.2.0 using a local installation, and everything works as expected.

For now I don't have any particular idea on how to implement the suggestion I made. I'll try to have a look in the coming days.

Thanks for your help!

**Comment by st--** [comment]
@lbteixeira I've updated the documentation, and hence closed this issue. Please open a new one for the color, if you are keen for it to stay on the radar!
