### ISSUE TITLE
Declare package's dependencies for CTAN

### ISSUE THREAD

**Issue by L-TChen** [st--/annotate-equations#22]
At least the package `pgf ` (for `tikz`) and `tikzmark` are required to use `annotate-equations`. It should be a good idea to declare the dependency on these packages by listing them in `DEPENDS.txt` (see the [usage](https://www.tug.org/texlive/pkgcontrib.html#deps)).

There are other tools to locate all dependencies, but I did not try.

**Comment by st--** [comment]
I've added these in commit 802efcf - will become part of the next release. Thanks for suggesting, I had no idea this existed! (And let me know if I made a mistake in preparing the DEPENDS.txt file.)
