### ISSUE TITLE
The `annotate` command adds a line after the equation if used outside the equation

### ISSUE THREAD

**Issue by munael** [st--/annotate-equations#24]
## Problem

When the `\annotate` command is used _outside_ the math environment (as the examples use it), and extra line/paragraph is added after the math environment.

If instead one puts the `\annotate` command inside the math environment, such before `\end{equation}`, then no extra line is added. The user then needs to add `\vspace` explicitly to add spacing for the annotation labels that are rendered `below`, which is consistent with the requirements for those rendered `above`.

### Output

**_Note the line `223`._**

![image](https://github.com/st--/annotate-equations/assets/5769148/e3900544-48ee-4864-9ae6-3856dfdd4c95)

### Code
```tex
Some text before.

\begin{equation}
    \eqnmark[red]{node1}{x} = \eqnmark[blue]{node2}{y}
\end{equation}
\annotate[yshift=0.2em]{above,left}{node1}{fubar X}
\annotate[yshift=0.2em]{above,right}{node2}{hello Y}

Some text after.

Some text before.

\begin{equation}
    \eqnmark[red]{node1}{x} = \eqnmark[blue]{node2}{y}
\annotate[yshift=0.2em]{above,left}{node1}{fubar X}
\annotate[yshift=0.2em]{above,right}{node2}{hello Y}
\end{equation}

Some text after.

Some text before.

\begin{equation}
    \eqnmark[red]{node1}{x} = \eqnmark[blue]{node2}{y}
\end{equation}

Some text after.
```

**Comment by munael** [comment]
## Explanation and Workaround

The `\annotate` command is treated as a paragraph started in some way. So if you put the text that comes later right after it, the line disappears. You can also put a commented line instead of a new line.

```tex
\begin{equation}
    \eqnmark[red]{node1}{x} = \eqnmark[blue]{node2}{y}
\end{equation}
\annotate[yshift=0.2em]{above,left}{node1}{fubar X}
\annotate[yshift=0.2em]{above,right}{node2}{hello Y}
% !!! This is changed from a mere new-line character in the original example.
% Any number of commented lines is the same as no new-line characters at all.
Some text after (no extra new-line).

Second paragraph (note the different indentation).
```

![image](https://github.com/st--/annotate-equations/assets/5769148/49587472-d02a-4d0d-9f22-cd7af94816b2)


## Another Caveat

The workaround does not work if the item that follows is complicated? Like a section. So the following doesn't work:

```tex
\begin{equation}
    \eqnmark[red]{node1}{x} = \eqnmark[blue]{node2}{y}
\end{equation}
\annotate[yshift=0.2em]{above,left}{node1}{fubar X}
\annotate[yshift=0.2em]{above,right}{node2}{hello Y}
%
% Does NOT work. New-line is still added!
%
\section{Section Title}
```

## Fix

I don't know enough of Latex to suggest how to make `\annotate` not do that, but will keep an eye out for updates to the package in hopes that it's fixed! Thanks for the great package 👍

**Comment by st--** [comment]
Hi, thanks for describing your issue - but could you please clarify what the "intended behaviour" should be in your mind? It's not clear to me which part is the problem / how you would want it to be instead. (Though I'm not a LaTeX guru and might not be able to figure out changing how the spacing behaves regardless...)

**Comment by st--** [comment]
It took me a while to realize, but I've now understood the issue and hopefully fixed it in #27. It's surprisingly easy to unintentionally add extra spaces through macros... One has to be super careful to have a `%` at the end of every line to eat up the line break as well as any indentation on the next line. And I missed a bunch ... so thanks for bringing this up!

Note that you will ALSO need to add the `%` at the end of your call to `\annotate`, i.e. your minimal example would have to be
```latex
\begin{equation}
    \eqnmark[red]{node1}{x} = \eqnmark[blue]{node2}{y}
\end{equation}
\annotate[yshift=0.2em]{above,left}{node1}{fubar X}%
\annotate[yshift=0.2em]{above,right}{node2}{hello Y}%
% !!! This is changed from a mere new-line character in the original example.
% Any number of commented lines is the same as no new-line characters at all.
Some text after (no extra new-line).

Second paragraph (note the different indentation).
```
This should now work as intended; until I've gotten around to make a new CTAN release & have it propagate through the distributions, please just take the `annotate-equations.sty` from the GitHub. Do let me know if it doesn't quite work as you expect it!

**Comment by st--** [comment]
And reopening this so that I also add a mention of the `%` at the end to the manual...

**Comment by st--** [comment]
Actually, created #28 to keep track of minor documentation clarifications such as this one.
