### ISSUE TITLE
[feature request] Annotation in multi-line equations

### ISSUE THREAD

**Issue by fmneto** [st--/annotate-equations#25]
Would be nice to be able to "connect" two boxes in subsequent lines with the same annotation. That would require the arrow to connect below one box, but above another.

**Comment by st--** [comment]
Do you mean multi-line equations like
```
a b = c d   (1)
^
|___
|
v
a e = f g  (2)
```
or what do you have in mind - could you upload a sketch of what you're trying to achieve?

**Comment by fmneto** [comment]
Yes, that's pretty much what I mean. 

_Maybe_ it would be desirable to do that to equations in different environments, but I expect that to be a lot more challenging and wouldn't presume to ask for it.

**Comment by st--** [comment]
Thanks for your patience! You can actually make this happen as follows, with just depending on `\usepackage{annotate-equations}` (and, implicitly, TikZ):

## With multiple `equation` environments:
```latex
\begin{equation}
    b \eqnmarkbox[blue]{a1}{a} = c d
\end{equation}
\vspace{1.5em}  % make some space for annotation
\begin{equation}
    \eqnmarkbox[red]{a2}{a} e = f g
\end{equation}
\begin{tikzpicture}[overlay,remember picture]
    % 
    \coordinate (a2above) at (a2.north);
\end{tikzpicture}
\annotate[yshift=-0.4em]{below}{a1,a2above}{some variable}
```
![image](https://github.com/user-attachments/assets/108237e9-3aac-4e70-913d-9c05da4e087a)


## With `align` environment (requires `\usepackage{amsmath}`):
```latex
\begin{align}
    w \eqnmarkbox[blue]{b1}{b} &= c d \\[2.2em]  % make some space for annotation
    l \eqnmarkbox[red]{b2}{b} &= f g
\end{align}
\begin{tikzpicture}[overlay,remember picture]
    \coordinate (b2above) at (b2.north);
\end{tikzpicture}
\annotate[yshift=-0.2em]{below}{b1,b2above}{another variable}
```
![image](https://github.com/user-attachments/assets/1edc59fe-0518-41d5-b395-9d3fefa4b289)

## Notes
- you may have to adjust the amount of space added between equations, and how much to yshift the label/nodes; automating this would be much more complex than simply doing binary search on the correct values yourself...
- I'm not sure if the `[overlay,remember picture]` option to the `tikzpicture` is actually needed... so feel free to leave it out, but if something doesn't work, try putting it back.

**Comment by st--** [comment]
Please feel free to re-open this issue if there's any subtleties I've not yet covered, it doesn't work for you as you wish, etc... :)

**Comment by fmneto** [comment]
Hi, thanks for taking so long to reply. That looks amazing, thank you so much!
