### ISSUE TITLE
can't annotate inline TikZ nodes

### ISSUE THREAD

**Issue by VincentTam** [st--/annotate-equations#29]
The following code returns an error.

```tex
\documentclass{standalone}
\usepackage{annotate-equations}
\begin{document}
\vbox to 10em {
    $$\tikzmarknode{p}{\tikz{\node{a};}}$$
}
\end{document}
```

![image](https://github.com/user-attachments/assets/89442207-86e5-44f8-b6ff-9e5f0b853d17)

**Comment by st--** [comment]
Hi @VincentTam , this is not an issue with the `annotate-equations` package, but with how you use `\tikzmarknode` itself: you get the same error if you replace the `\usepackage{annotate-equations}` with `\usepackage{tikz} \usetikzlibrary{tikzmark}` instead.

`\tikzmarknode` is wrapping its argument already, so I don't think it's supposed to handle having another `\tikz` inside it. If you want to mark a TikZ node, according to the tikzmark manual you should instead use `\tikzmark[\node{a}]{p}` (but then you might as well just refer to the node directly and simply write `\tikz \node (p) {a};`).
