### ISSUE TITLE
Arrow invades term in the formula if there is mismatch between `yshift` and selected `above`/`below` option

### ISSUE THREAD

**Issue by pauloney** [st--/annotate-equations#5]
The arrow with the comment sometimes invade a sign in the middle of the formula.

```
\documentclass{report}
\usepackage{annotate-equations}

\begin{document}
\[
        \sum_{i=1}^n E(X_i|S=s) \mathrel{\tikzmarknode{node5}{=}} E\left(\sum_{i=1}^n X_i|S=s\right)
\]
\annotate[yshift=-3.5em]{above}{node5}{por linearidade}

\end{document}
```

![image](https://user-images.githubusercontent.com/2358114/202967403-2b1ad615-d8ba-4760-ba6a-ff40074b82c8.png)

**Comment by st--** [comment]
You requested the annotation to be `above` but moved it down: if you swap it as follows,
```diff
-\annotate[yshift=-3.5em]{above}{node5}{por linearidade}
+\annotate[yshift=-3.5em]{below}{node5}{por linearidade}
```
it renders fine.

An automatic solution that does away with the need for specifying above/below is beyond my current LaTeX skills - if anyone has an idea for how to do it, I'd happily check out a pull request though!

**Comment by st--** [comment]
I've clarified this in #9 as well.
