### ISSUE TITLE
Is it possible to use `xelatex` (answer: yes, just not tested as much)

### ISSUE THREAD

**Issue by pauloney** [st--/annotate-equations#6]
The manual mentions (mora than once) that it should be processed with  `pdflatex` or `lualatex`. I have use it with `xelatex` with equal results. Why is it xelatex not mentioned?

**Comment by st--** [comment]
Simply because I've never used xelatex (and didn't even know about it), and I would not want to claim compatibility without having tested something! For some reason I had thought xelatex would require me to change the tex source, but `xelatex annotate-equations.tex` seems to work just fine.

**Comment by st--** [comment]
Where does the manual mention this? I can't find any mention in the docs themselves, and only one on the CTAN page..

**Comment by pauloney** [comment]
It is written like that on the CTAN and GitHub sites:

https://github.com/st--/annotate-equations

  Should work with pdfLATEX as well as LuaLATEX.

**Comment by st--** [comment]
Ah, it didn't occur to me someone would read that as "does NOT work with XeLaTeX"... I'll change it

**Comment by st--** [comment]
Thanks for pointing this out, @pauloney !
