### ISSUE TITLE
Need to process twice

### ISSUE THREAD

**Issue by pauloney** [st--/annotate-equations#7]
As a positioning solution using TikZ, it needs to be processed twice before getting everything in the proper place. I  have not seen that mentioned in the manual. My suggestion is for right afte the text:

```
There is still a bit of manual tweaking required (such as adding vertical space before/after the
equation), but hopefully this package will already make it a bit more inviting to annotate your equations!
```

on the top of the first page.

**Comment by st--** [comment]
Thank you, that's a great suggestion. I'd gotten used to just running `latexmk` all the time, so I didn't even think of it - but of course it would be better to be explicit, for those who run things manually!

**Comment by st--** [comment]
I've edited the docs in #8, please have a look and let me know if you have any further comments on this:)
